### ISSUE TITLE
Choose a flux implementation

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/converter-flux#1]
Reqs:
- Async
- Server-side render
- Small
- No singletons

Candidates
- https://github.com/acdlite/flummox
- https://github.com/yahoo/fluxible

**Comment by kenwheeler** [comment]
+1 for Alt

**Comment by kenwheeler** [comment]
Flummox taking a very close second place

**Comment by ryan-roemer** [comment]
Alt wins!
