### ISSUE TITLE
Replace es6-promise with non-RSVP-based lib.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/converter-flux#12]
Maybe Bluebird?

**Comment by ryan-roemer** [comment]
Bluebird!

**Comment by divmain** [comment]
@ryan-roemer - bluebird is largish, which has been the only objection I've had to the library.  Fortunately, it is possible to do custom builds with subsets of functionality to bring down the file size.  Probably not appropriate for a starter like this, but something to keep in mind as a new component/project moves towards production deployment.
